services:
  - type: web
    name: osamap2-backend
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: TMDB_API_KEY
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: PORT
        value: 5000
