FOREIGN_SITES = [
    {'name': 'cineby.cc', 'url': 'https://cineby.cc', 'iframe_sel': 'iframe[src*="embed"]', 'video_sel': 'video source[src*=".m3u8"], video source[src*=".mp4"]'},
    {'name': 'streamex.net', 'url': 'https://streamex.net', 'iframe_sel': 'iframe[src*="embed"]', 'video_sel': 'video source[src*=".m3u8"]'},
    {'name': 'hydrahd.com', 'url': 'https://hydrahd.com', 'iframe_sel': 'iframe[src*="embed"]', 'video_sel': 'video source[src*=".m3u8"]'},
    {'name': 'nunflix.cc', 'url': 'https://nunflix.cc', 'iframe_sel': 'iframe[src*="embed"]', 'video_sel': 'video source[src*=".m3u8"]'},
    {'name': 'rivestream.com', 'url': 'https://rivestream.com', 'iframe_sel': 'iframe[src*="embed"]', 'video_sel': 'video source[src*=".m3u8"]'},
    {'name': 'watchug.com', 'url': 'https://watchug.com', 'iframe_sel': 'iframe[src*="embed"]', 'video_sel': 'video source[src*=".m3u8"]'},
    {'name': 'vidbox.tv', 'url': 'https://vidbox.tv', 'iframe_sel': 'iframe[src*="embed"]', 'video_sel': 'video source[src*=".m3u8"]'},
    {'name': 'broflix.org', 'url': 'https://broflix.org', 'iframe_sel': 'iframe[src*="embed"]', 'video_sel': 'video source[src*=".m3u8"]'},
    {'name': 'flickystream.com', 'url': 'https://flickystream.com', 'iframe_sel': 'iframe[src*="embed"]', 'video_sel': 'video source[src*=".m3u8"]'},
    {'name': 'mapple.tv', 'url': 'https://mapple.tv', 'iframe_sel': 'iframe[src*="embed"]', 'video_sel': 'video source[src*=".m3u8"]'},
    {'name': 'alienflix.com', 'url': 'https://alienflix.com', 'iframe_sel': 'iframe[src*="embed"]', 'video_sel': 'video source[src*=".m3u8"]'},
    {'name': 'novastream.to', 'url': 'https://novastream.to', 'iframe_sel': 'iframe[src*="embed"]', 'video_sel': 'video source[src*=".m3u8"]'},
    {'name': 'tubitv.com', 'url': 'https://tubitv.com', 'iframe_sel': '', 'video_sel': 'video[src*=".m3u8"]'},
    {'name': 'plutotv.com', 'url': 'https://plutotv.com', 'iframe_sel': '', 'video_sel': 'video[src*=".m3u8"]'},
    {'name': 'crackle.com', 'url': 'https://crackle.com', 'iframe_sel': 'iframe[src*="embed"]', 'video_sel': 'video source[src*=".m3u8"]'},
    {'name': 'therokuchannel.roku.com', 'url': 'https://therokuchannel.roku.com', 'iframe_sel': '', 'video_sel': 'video[src*=".m3u8"]'},
    {'name': 'amazon.com/adlp/freevee', 'url': 'https://amazon.com/adlp/freevee', 'iframe_sel': '', 'video_sel': ''},
    {'name': 'peacocktv.com', 'url': 'https://peacocktv.com', 'iframe_sel': '', 'video_sel': ''},
    {'name': 'plex.tv', 'url': 'https://plex.tv', 'iframe_sel': 'iframe[src*="embed"]', 'video_sel': 'video source[src*=".m3u8"]'},
    {'name': 'vudu.com', 'url': 'https://vudu.com', 'iframe_sel': '', 'video_sel': ''},
]

ARABIC_SITES = [
    {'name': 'arabseed.ws', 'url': 'https://arabseed.ws', 'iframe_sel': 'iframe[src*="embed"]', 'video_sel': 'video source[src*=".m3u8"]'},
    {'name': 'akwam.cc', 'url': 'https://akwam.cc', 'iframe_sel': 'iframe[src*="embed"]', 'video_sel': 'video source[src*=".m3u8"]'},
    {'name': 'faselplus.cc', 'url': 'https://faselplus.cc', 'iframe_sel': 'iframe[src*="embed"]', 'video_sel': 'video source[src*=".m3u8"]'},
    {'name': 'mycima.video', 'url': 'https://mycima.video', 'iframe_sel': 'iframe[src*="embed"]', 'video_sel': 'video source[src*=".m3u8"]'},
    {'name': 'cimaclub.com', 'url': 'https://cimaclub.com', 'iframe_sel': 'iframe[src*="embed"]', 'video_sel': 'video source[src*=".m3u8"]'},
    {'name': '3isk.tv', 'url': 'https://3isk.tv', 'iframe_sel': 'iframe[src*="embed"]', 'video_sel': 'video source[src*=".m3u8"]'},
    {'name': 'qrmzi.com', 'url': 'https://qrmzi.com', 'iframe_sel': 'iframe[src*="embed"]', 'video_sel': 'video source[src*=".m3u8"]'},
    {'name': 'watanflix.com', 'url': 'https://watanflix.com', 'iframe_sel': 'iframe[src*="embed"]', 'video_sel': 'video source[src*=".m3u8"]'},
    {'name': 'egybest.com', 'url': 'https://egybest.com', 'iframe_sel': 'iframe[src*="embed"]', 'video_sel': 'video source[src*=".m3u8"]'},
    {'name': 'elcinema.com', 'url': 'https://elcinema.com', 'iframe_sel': '', 'video_sel': 'video source[src*=".mp4"]'},
    {'name': 'a.qfilm.tv', 'url': 'https://a.qfilm.tv', 'iframe_sel': 'iframe[src*="embed"]', 'video_sel': ''},
    {'name': 'r.cimalight.co', 'url': 'https://r.cimalight.co', 'iframe_sel': 'iframe[src*="embed"]', 'video_sel': ''},
    {'name': 'shoofdrama.com', 'url': 'https://shoofdrama.com', 'iframe_sel': 'iframe[src*="embed"]', 'video_sel': 'video source[src*=".m3u8"]'},
    {'name': 'laroza.video', 'url': 'https://laroza.video', 'iframe_sel': 'iframe[src*="embed"]', 'video_sel': 'video source[src*=".m3u8"]'},
    {'name': 'hekat-tv.com', 'url': 'https://hekat-tv.com', 'iframe_sel': 'iframe[src*="embed"]', 'video_sel': 'video source[src*=".m3u8"]'},
    {'name': 'dramaturkey.com', 'url': 'https://dramaturkey.com', 'iframe_sel': 'iframe[src*="embed"]', 'video_sel': ''},
    {'name': 'hilalplay.com', 'url': 'https://hilalplay.com', 'iframe_sel': '', 'video_sel': 'video[src*=".mp4"], source[src*=".mp4"]'},
    {'name': 'shahid.mbc.net', 'url': 'https://shahid.mbc.net', 'iframe_sel': '', 'video_sel': 'video[src*=".m3u8"]'},
    {'name': 'starzplay.com', 'url': 'https://starzplay.com', 'iframe_sel': '', 'video_sel': ''},
    {'name': 'viu.com', 'url': 'https://viu.com', 'iframe_sel': '', 'video_sel': ''},
]

TURKISH_SITES = [
    {'name': 'kayifamily.com', 'url': 'https://kayifamily.com', 'iframe_sel': 'iframe[src*="embed"]', 'video_sel': 'video source[src*=".m3u8"]'},
    {'name': 'dizipal.com', 'url': 'https://dizipal.com', 'iframe_sel': 'iframe[src*="embed"]', 'video_sel': 'video source[src*=".m3u8"]'},
    {'name': 'diziwatch.net', 'url': 'https://diziwatch.net', 'iframe_sel': 'iframe[src*="embed"]', 'video_sel': 'video source[src*=".m3u8"]'},
    {'name': 'fullhdfilmizle.com', 'url': 'https://fullhdfilmizle.com', 'iframe_sel': 'iframe[src*="embed"]', 'video_sel': 'video source[src*=".m3u8"]'},
    {'name': 'dizigom.net', 'url': 'https://dizigom.net', 'iframe_sel': 'iframe[src*="embed"]', 'video_sel': 'video source[src*=".m3u8"]'},
    {'name': 'dizibox.com', 'url': 'https://dizibox.com', 'iframe_sel': 'iframe[src*="embed"]', 'video_sel': 'video source[src*=".m3u8"]'},
    {'name': 'turkish123.com', 'url': 'https://turkish123.com', 'iframe_sel': 'iframe[src*="embed"]', 'video_sel': ''},
    {'name': 'diziyou.com', 'url': 'https://diziyou.com', 'iframe_sel': 'iframe[src*="embed"]', 'video_sel': 'video source[src*=".m3u8"]'},
    {'name': 'blutv.com', 'url': 'https://blutv.com', 'iframe_sel': '', 'video_sel': 'video[src*=".m3u8"]'},
    {'name': 'puhutv.com', 'url': 'https://puhutv.com', 'iframe_sel': '', 'video_sel': 'video[src*=".m3u8"]'},
    {'name': 'turkflix.net', 'url': 'https://turkflix.net', 'iframe_sel': 'iframe[src*="embed"]', 'video_sel': 'video source[src*=".m3u8"]'},
    {'name': 'osmanonline.com', 'url': 'https://osmanonline.com', 'iframe_sel': 'iframe[src*="embed"]', 'video_sel': ''},
    {'name': 'dizimania.com', 'url': 'https://dizimania.com', 'iframe_sel': 'iframe[src*="embed"]', 'video_sel': 'video source[src*=".m3u8"]'},
    {'name': 'yoturkish.com', 'url': 'https://yoturkish.com', 'iframe_sel': 'iframe[src*="embed"]', 'video_sel': ''},
    {'name': 'serial4u.com', 'url': 'https://serial4u.com', 'iframe_sel': 'iframe[src*="embed"]', 'video_sel': 'video source[src*=".m3u8"]'},
    {'name': 'promix.tv', 'url': 'https://promix.tv', 'iframe_sel': '', 'video_sel': ''},
    {'name': 'dizistar.com', 'url': 'https://dizistar.com', 'iframe_sel': 'iframe[src*="embed"]', 'video_sel': ''},
    {'name': 'teknoasian.com', 'url': 'https://teknoasian.com', 'iframe_sel': 'iframe[src*="embed"]', 'video_sel': 'video source[src*=".m3u8"]'},
    {'name': 'sinemalar.com', 'url': 'https://sinemalar.com', 'iframe_sel': '', 'video_sel': ''},
    {'name': 'hdfilmcehennemi.com', 'url': 'https://hdfilmcehennemi.com', 'iframe_sel': 'iframe[src*="embed"]', 'video_sel': 'video source[src*=".m3u8"]'},
]

ANIME_SITES = [
    {'name': 'hianime.to', 'url': 'https://hianime.to', 'iframe_sel': 'iframe[src*="embed"]', 'video_sel': 'video source[src*=".m3u8"]'},
    {'name': 'anime-defenders.com', 'url': 'https://anime-defenders.com', 'iframe_sel': 'iframe[src*="embed"]', 'video_sel': 'video source[src*=".m3u8"]'},
    {'name': 'anigo.one', 'url': 'https://anigo.one', 'iframe_sel': 'iframe[src*="embed"]', 'video_sel': 'video source[src*=".m3u8"]'},
    {'name': 'jkanime.net', 'url': 'https://jkanime.net', 'iframe_sel': 'iframe[src*="embed"]', 'video_sel': 'video source[src*=".m3u8"]'},
    {'name': 'animeunity.tv', 'url': 'https://animeunity.tv', 'iframe_sel': 'iframe[src*="embed"]', 'video_sel': 'video source[src*=".m3u8"]'},
    {'name': 'anitaku.to', 'url': 'https://anitaku.to', 'iframe_sel': 'iframe[src*="embed"]', 'video_sel': 'video source[src*=".m3u8"]'},
    {'name': 'miruro.tv', 'url': 'https://miruro.tv', 'iframe_sel': 'iframe[src*="embed"]', 'video_sel': 'video source[src*=".m3u8"]'},
    {'name': 'aniwave.to', 'url': 'https://aniwave.to', 'iframe_sel': 'iframe[src*="embed"]', 'video_sel': 'video source[src*=".m3u8"]'},
    {'name': 'animeyat.net', 'url': 'https://animeyat.net', 'iframe_sel': 'iframe[src*="embed"]', 'video_sel': 'video source[src*=".m3u8"]'},
    {'name': 'animeout.xyz', 'url': 'https://animeout.xyz', 'iframe_sel': 'iframe[src*="embed"]', 'video_sel': 'video source[src*=".m3u8"]'},
    {'name': 'animeblix.com', 'url': 'https://animeblix.com', 'iframe_sel': 'iframe[src*="embed"]', 'video_sel': 'video source[src*=".m3u8"]'},
    {'name': 'animixplay.to', 'url': 'https://animixplay.to', 'iframe_sel': 'iframe[src*="embed"]', 'video_sel': 'video source[src*=".m3u8"]'},
    {'name': 'witanime.com', 'url': 'https://witanime.com', 'iframe_sel': 'iframe[src*="embed"]', 'video_sel': 'video source[src*=".m3u8"]'},
    {'name': 'anime4up.com', 'url': 'https://anime4up.com', 'iframe_sel': 'iframe[src*="embed"]', 'video_sel': 'video source[src*=".m3u8"]'},
    {'name': 'shahiid-anime.net', 'url': 'https://shahiid-anime.net', 'iframe_sel': 'iframe[src*="embed"]', 'video_sel': 'video source[src*=".m3u8"]'},
    {'name': 'anime3rb.com', 'url': 'https://anime3rb.com', 'iframe_sel': 'iframe[src*="embed"]', 'video_sel': 'video source[src*=".m3u8"]'},
    {'name': 'animeslayer.to', 'url': 'https://animeslayer.to', 'iframe_sel': 'iframe[src*="embed"]', 'video_sel': 'video source[src*=".m3u8"]'},
    {'name': 'animekaizoku.com', 'url': 'https://animekaizoku.com', 'iframe_sel': 'iframe[src*="embed"]', 'video_sel': 'video source[src*=".m3u8"]'},
    {'name': 'animovitch.com', 'url': 'https://animovitch.com', 'iframe_sel': 'iframe[src*="embed"]', 'video_sel': 'video source[src*=".m3u8"]'},
    {'name': 'animegon.com', 'url': 'https://animegon.com', 'iframe_sel': 'iframe[src*="embed"]', 'video_sel': 'video source[src*=".m3u8"]'},
]

SOURCES = {
    'foreign': FOREIGN_SITES,
    'arabic': ARABIC_SITES,
    'turkish': TURKISH_SITES,
    'anime': ANIME_SITES,
}
